#!/usr/bin/env bash
# Build a distributable ClipBridge.app bundle and wrap it in a DMG.
#
#   ./scripts/build-macos-app.sh                  # native arch only (fast)
#   ./scripts/build-macos-app.sh --universal      # arm64 + x86_64 via lipo
#   ./scripts/build-macos-app.sh --no-dmg         # skip the DMG step
#
# Output:
#   build/macos/ClipBridge.app
#   build/macos/ClipBridge.dmg          (drag-to-Applications installer)
#
# Install for end user:
#   double-click ClipBridge.dmg → drag ClipBridge.app onto Applications
#
# First launch from /Applications shows Gatekeeper warning (we only ad-hoc
# sign). Right-click → Open once and macOS remembers the choice.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

NATIVE_ARCH=$(uname -m)
ARCHS=("$NATIVE_ARCH")
MAKE_DMG=1
while [[ $# -gt 0 ]]; do
  case "$1" in
    --arch)
      ARCHS=("$2")
      shift 2
      ;;
    --universal)
      # SwiftPM's two `--arch` flags trip an `ld` assertion on linking ObjC
      # metadata, so we build each arch separately and lipo them together.
      ARCHS=(arm64 x86_64)
      shift
      ;;
    --no-dmg)
      MAKE_DMG=0
      shift
      ;;
    *)
      echo "unknown flag: $1" >&2
      exit 1
      ;;
  esac
done

OUT_DIR="$ROOT/build/macos"
APP="$OUT_DIR/ClipBridge.app"
BUNDLE_ID="com.clipbridge.mac"
VERSION="0.1.0"
MIN_OS="13.0"

cd "$ROOT"

# 1. Build clipbridge-core into a universal macOS xcframework + Swift glue.
#    SwiftPM's binary target under clients/macos consumes the xcframework.
echo "==> 1/4 rebuilding xcframework"
XCF_OUT="$ROOT/build/macos"
XCF_HEADERS="$XCF_OUT/headers"
PROFILE_DIR="release"
mkdir -p "$XCF_HEADERS" "$XCF_OUT/universal"

echo "    -> aarch64-apple-darwin"
cargo build --release -p clipbridge-core --target aarch64-apple-darwin >/dev/null
echo "    -> x86_64-apple-darwin"
cargo build --release -p clipbridge-core --target x86_64-apple-darwin >/dev/null

lipo -create \
  "target/aarch64-apple-darwin/$PROFILE_DIR/libclipbridge_core.a" \
  "target/x86_64-apple-darwin/$PROFILE_DIR/libclipbridge_core.a" \
  -output "$XCF_OUT/universal/libclipbridge_core.a"

echo "    -> swift bindings"
cargo run -p uniffi-bindgen -- generate \
  --library "target/aarch64-apple-darwin/$PROFILE_DIR/libclipbridge_core.dylib" \
  --language swift \
  --out-dir "$XCF_OUT" >/dev/null

mv "$XCF_OUT/clipbridge_coreFFI.h" "$XCF_HEADERS/"
mv "$XCF_OUT/clipbridge_coreFFI.modulemap" "$XCF_HEADERS/module.modulemap"

rm -rf "$XCF_OUT/ClipbridgeCore.xcframework"
xcodebuild -create-xcframework \
  -library "$XCF_OUT/universal/libclipbridge_core.a" \
  -headers "$XCF_HEADERS" \
  -output "$XCF_OUT/ClipbridgeCore.xcframework" >/dev/null

# Keep the SwiftPM target's source file in sync. The xcframework itself is
# symlinked under clients/macos but the .swift glue is a real copy and would
# otherwise drift.
SWIFTPM_GLUE="$ROOT/clients/macos/Sources/ClipbridgeCore/clipbridge_core.swift"
if [[ -f "$SWIFTPM_GLUE" || -d "$(dirname "$SWIFTPM_GLUE")" ]]; then
  cp "$XCF_OUT/clipbridge_core.swift" "$SWIFTPM_GLUE"
fi

echo "==> 2/4 swift build (release, archs: ${ARCHS[*]})"
cd "$ROOT/clients/macos"

PER_ARCH_BINS=()
for a in "${ARCHS[@]}"; do
  echo "    -> $a"
  swift build -c release --arch "$a" >/dev/null
  PER_ARCH_BINS+=("$ROOT/clients/macos/.build/${a}-apple-macosx/release/ClipBridgeApp")
done

EXEC="$ROOT/build/macos/ClipBridgeApp"
mkdir -p "$ROOT/build/macos"
if [[ ${#PER_ARCH_BINS[@]} -gt 1 ]]; then
  lipo -create "${PER_ARCH_BINS[@]}" -output "$EXEC"
else
  cp "${PER_ARCH_BINS[0]}" "$EXEC"
fi
[[ -f "$EXEC" ]] || { echo "executable not built" >&2; exit 1; }

echo "==> 3/4 assembling $APP"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$EXEC" "$APP/Contents/MacOS/ClipBridge"

# Bundle icon — generated by scripts/regen-icons.sh from assets/icon.svg.
# Skipped (with a warning) if missing so the bundle still assembles for
# someone who hasn't run the icon regen yet.
ICNS_SRC="$ROOT/clients/macos/Resources/AppIcon.icns"
HAS_ICON=0
if [[ -f "$ICNS_SRC" ]]; then
  cp "$ICNS_SRC" "$APP/Contents/Resources/AppIcon.icns"
  HAS_ICON=1
else
  echo "    [warn] $ICNS_SRC missing — run scripts/regen-icons.sh to add the bundle icon"
fi

cat >"$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleIdentifier</key>           <string>$BUNDLE_ID</string>
    <key>CFBundleName</key>                  <string>ClipBridge</string>
    <key>CFBundleDisplayName</key>           <string>ClipBridge</string>
    <key>CFBundleExecutable</key>            <string>ClipBridge</string>$([[ $HAS_ICON -eq 1 ]] && printf '\n    <key>CFBundleIconFile</key>            <string>AppIcon</string>')
    <key>CFBundleVersion</key>               <string>$VERSION</string>
    <key>CFBundleShortVersionString</key>    <string>$VERSION</string>
    <key>CFBundlePackageType</key>           <string>APPL</string>
    <key>CFBundleSignature</key>             <string>????</string>
    <key>CFBundleInfoDictionaryVersion</key> <string>6.0</string>
    <!-- LSUIElement = menu-bar-only app, no Dock icon, no main window. -->
    <key>LSUIElement</key>                   <true/>
    <key>LSMinimumSystemVersion</key>        <string>$MIN_OS</string>
    <key>NSHighResolutionCapable</key>       <true/>
    <key>NSHumanReadableCopyright</key>      <string>© 2026 ClipBridge</string>
    <key>NSSupportsAutomaticTermination</key> <false/>
    <key>NSSupportsSuddenTermination</key>   <true/>
    <!-- LAN peer discovery (mDNS / DNS-SD). macOS Sonoma+ requires both
         a usage string and an explicit list of advertised service types
         before the app is allowed to send/receive multicast on the local
         network. Without these the user is never prompted and mDNS
         silently fails — the app falls back to relay-only. -->
    <key>NSLocalNetworkUsageDescription</key>
    <string>用于在同一局域网内发现其它 ClipBridge 设备并直连传输, 无需经过中继服务器。</string>
    <key>NSBonjourServices</key>
    <array>
        <string>_clipbridge._tcp</string>
    </array>
</dict>
</plist>
PLIST

echo "==> 4/4 ad-hoc codesign"
codesign --force --deep --sign - "$APP" >/dev/null

DMG=""
if [[ $MAKE_DMG -eq 1 ]]; then
  echo "==> 5/5 building DMG"
  DMG="$OUT_DIR/ClipBridge.dmg"
  STAGE="$OUT_DIR/.dmg-stage"
  rm -rf "$STAGE" "$DMG"
  mkdir -p "$STAGE"
  cp -R "$APP" "$STAGE/"
  # Drag-to-Applications shortcut so the user can install with a flick.
  ln -s /Applications "$STAGE/Applications"

  # UDZO = zlib-compressed read-only disk image. About 1/3 the size of the
  # uncompressed bundle for a Rust+Swift binary like ours.
  hdiutil create \
    -volname "ClipBridge" \
    -srcfolder "$STAGE" \
    -fs HFS+ \
    -format UDZO \
    -ov \
    "$DMG" >/dev/null

  rm -rf "$STAGE"
fi

# Drop the staging executable used for assembly (the .app keeps its own copy).
rm -f "$EXEC"

SIZE=$(du -sh "$APP" | cut -f1)
ARCHS_STR=$(lipo -archs "$APP/Contents/MacOS/ClipBridge")

echo
echo "✓ Bundle:    $APP ($SIZE, $ARCHS_STR)"
[[ -n "$DMG" ]] && echo "✓ DMG:       $DMG ($(du -sh "$DMG" | cut -f1))"
echo "✓ BundleID:  $BUNDLE_ID"
echo
if [[ -n "$DMG" ]]; then
  echo "Open:        open '$DMG'"
  echo "             then drag ClipBridge to the Applications shortcut."
fi
echo "Try direct:  open '$APP'"
echo "Autostart:   状态栏菜单 → 开机自启 (使用 SMAppService 注册 Login Item)"
echo "Note:        First launch may need Right-click → Open (Gatekeeper)"
